import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('textbox', { name: '1234567890' }).click();
  await page.getByRole('textbox', { name: '1234567890' }).click();
  await page.getByRole('textbox', { name: '1234567890' }).fill('18866');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('Gael2026@');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('link', { name: ' Panel Principal' }).click();
  await page.getByRole('link', { name: ' Mis Requisiciones' }).click();
  await page.getByRole('link', { name: ' Aprobaciones' }).click();
  await page.getByRole('row', { name: '#REQ-6144 PRUEBAS 2 21/4/2026' }).getByRole('button').click();
  await page.locator('div').filter({ hasText: 'Detalle de Requisición ID:' }).nth(1).click();
  await page.locator('div').filter({ hasText: 'Detalle de Requisición ID:' }).nth(1).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('row', { name: '#REQ-5706 RECARGA DE SALDO EL' }).getByRole('button').click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: ' Panel Principal' }).click();
  await page.getByRole('textbox', { name: 'Buscar requisiciones, folios' }).click();
  await page.getByRole('textbox', { name: 'Buscar requisiciones, folios' }).fill('fawfa');
  await page.getByRole('button', { name: ' Actualizar' }).click();
  await page.getByRole('button', { name: '+ Crear Requisición' }).click();
  await page.locator('#usuarioAutorizador').selectOption('CAPTURACION');
  await page.locator('#proceso').selectOption('COMERCIALIZACION Y VENTA');
  await page.getByRole('textbox', { name: 'Ej: Renovación de equipo' }).click();
  await page.getByRole('textbox', { name: 'Ej: Renovación de equipo' }).fill('awdawd');
  await page.locator('#planta').selectOption('APTIV CENTEC 2 COBRO');
  await page.locator('#region').selectOption('DURANGO');
  await page.locator('#fechaEntrega').fill('2026-10-10');
  await page.locator('div').filter({ hasText: 'Usuario Autorizador *' }).nth(3).click();
  await page.getByRole('textbox', { name: '**** **** ****' }).click();
  await page.getByRole('textbox', { name: '**** **** ****' }).fill('232323');
  await page.locator('div').filter({ hasText: 'Usuario Autorizador *' }).nth(3).click();
  await page.getByRole('textbox', { name: 'OV-00000-CO-' }).click();
  await page.getByRole('textbox', { name: 'OV-00000-CO-' }).fill('awdad');
  await page.getByRole('checkbox', { name: 'Gasto Directo' }).check();
});