import { DataTypes, Sequelize } from "sequelize";
// const sequelize = new Sequelize('sqlite::memory:');
import db from "../config/db.js";

const Vales = db.define('vales', {
    iddepartamento,
    idpuesto,
    idtipoperiodo,
    idturno,
    codigoempleado,
    nombre,
    fotografia,
    apellidopaterno,
    apellidomaterno,
    nombrelargo,
    fechanacimiento,
    lugarnacimiento,
    estadocivil,
    sexo,
    curpi,
    curpf,
    numerosegurosocial,
    umf,
    rfc,
    homoclave,
    cuentapagoelectronico,
    sucursalpagoelectronico,
    bancopagoelectronico,
    estadoempleado,
    sueldodiario,
    fechasueldodiario,
    sueldovariable,
    fechasueldovariable,
    sueldopromedio,
    fechasueldopromedio,
    sueldointegrado,
    fechasueldointegrado,
    calculado,
    afectado,
    calculadoextraordinario,
    afectadoextraordinario,
    interfazcheqpaqw,
    modificacionneto,
    fechaalta,
    cuentacw,
    tipocontrato,
    basecotizacionimss,
    tipoempleado,
    basepago,
    formapago,
    zonasalario,
    calculoptu,
    calculoaguinaldo,
    modificacionsalarioimss,
    altaimss,
    bajaimss,
    cambiocotizacionimss,
    expediente,
    telefono,
    codigopostal,
    direccion,
    poblacion,
    estado,
    nombrepadre,
    nombremadre,
    numeroafore,
    fechabaja,
    causabaja,
    sueldobaseliquidacion,
    campoextra1,
    campoextra2,
    campoextra3,
    fechareingreso,
    ajustealneto,
    timestamp,
    cidregistropatronal,
    ccampoextranumerico1,
    ccampoextranumerico2,
    ccampoextranumerico3,
    ccampoextranumerico4,
    ccampoextranumerico5,
    cestadoempleadoperiodo,
    cfechasueldomixto,
    csueldomixto,
    NumeroFonacot,
    CorreoElectronico,
    TipoRegimen,
    ClabeInterbancaria,
    EntidadFederativa,
    Subcontratacion,
    ExtranjeroSinCURP,
    TipoPrestacion,
    DiasVacTomadasAntesdeAlta,
    DiasPrimaVacTomadasAntesdeAlta,
    TipoSemanaReducida,
    Teletrabajador,
    Equipo,
    Insumo,
    DireccionTeletrabajo,
    idLider,
    checkColabora
},{
    tableName: 'vales',
    // sequelize,
    freezeTableName: true, // Desactiva la pluralización automática
    timestamps: false
});

export default Vales;